# Exercicis

Intenta utilitzar les funcions de `pandas` tant com puguis.

**No** facis servir cap `if` o `for` de Python.

**No** sobreescriguis la variable `df` enlloc (a no ser que es demani explicitament), mantén-la tal com està.

In [1]:
from random import random

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from fontTools.misc.cython import returns

In [2]:
df = pd.read_csv('../data/occupation.csv', sep='|')
print(df)

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

## Mostra els 10 primers elements del DataFrame.

In [3]:
deu_primers = df.head(10)
deu_primers

   user_id  age gender     occupation zip_code
0        1   24      M     technician    85711
1        2   53      F          other    94043
2        3   23      M         writer    32067
3        4   24      M     technician    43537
4        5   33      F          other    15213
5        6   42      M      executive    98101
6        7   57      M  administrator    91344
7        8   36      M  administrator    05201
8        9   29      M        student    01002
9       10   53      M         lawyer    90703

## Mostra els 8 últims elements del DataFrame.

In [4]:
df.tail(8)

     user_id  age gender     occupation zip_code
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

## Quantes ocupacions diferents hi ha al conjunt de dades?

**Pista**: `nunique()`

In [5]:
#df.columns
df['occupation'].nunique()

21

## Quants gèneres diferents hi ha?

**Pista**: `unique()`

In [6]:
len(df['gender'].unique())

2

## Quants elements hi ha per a cada gènere?

**Pista**: `value_counts()`

In [7]:
df['gender'].value_counts()

gender
M    670
F    273
Name: count, dtype: int64

## Mostra els individus amb 16 anys o més.

In [8]:
individus = df[df['age']>=16]
individus

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[926 rows x 5 columns]

## Mostra els individus amb edats entre 30 i 40 anys, ambdós inclosos.

In [9]:
individus_trenta_cuarenta = df[(df['age']>=30) & (df['age']<=40)]
individus_trenta_cuarenta

     user_id  age gender     occupation zip_code
4          5   33      F          other    15213
7          8   36      M  administrator    05201
10        11   39      F          other    30329
16        17   30      M     programmer    06355
17        18   35      F          other    37212
..       ...  ...    ...            ...      ...
910      911   37      F         writer    53210
917      918   40      M      scientist    70116
919      920   30      F         artist    90008
937      938   38      F     technician    55038
939      940   32      M  administrator    02215

[262 rows x 5 columns]

## Mostra les dones entre 30 i 35 anys que treballen com a educadores.

In [10]:
#df['gender'].unique()
df[(df['gender'] == 'F') & (df['occupation'] == 'educator') & (df['age'].between(30,35))]

     user_id  age gender occupation zip_code
151      152   33      F   educator    68767
208      209   33      F   educator    85710
223      224   31      F   educator    43512
329      330   35      F   educator    33884
449      450   35      F   educator    11758
555      556   35      F   educator    30606
592      593   31      F   educator    68767

## Mostra els individus homes que treballen com a tècnics o escriptors.

In [11]:
hombres = df[(df['gender'] == 'M') & (df['occupation'].isin(['technician', 'writer']))]
hombres

     user_id  age gender  occupation zip_code
0          1   24      M  technician    85711
2          3   23      M      writer    32067
3          4   24      M  technician    43537
20        21   26      M      writer    30068
21        22   25      M      writer    40206
27        28   32      M      writer    55369
43        44   26      M  technician    46260
49        50   21      M      writer    52245
76        77   30      M  technician    29379
142      143   42      M  technician    08832
195      196   49      M      writer    55105
196      197   55      M  technician    75094
198      199   30      M      writer    17604
200      201   27      M      writer    E2A4H
243      244   28      M  technician    80525
292      293   24      M      writer    60804
293      294   34      M  technician    92110
310      311   32      M  technician    73071
324      325   48      M  technician    02139
369      370   52      M      writer    08534
384      385   36      M      writer    10003
391      392   52      M      writer    59801
440      441   50      M  technician    55013
444      445   21      M      writer    92653
455      456   24      M  technician    31820
457      458   47      M  technician    Y1A6B
463      464   60      M      writer    94583
487      488   48      M  technician    21012
497      498   26      M      writer    55408
544      545   27      M  technician    08052
547      548   51      M      writer    95468
669      670   30      M  technician    21114
694      695   26      M      writer    38115
714      715   21      M  technician    91206
716      717   24      M  technician    84105
717      718   42      M  technician    64118
737      738   35      M  technician    95403
738      739   35      M  technician    73162
740      741   25      M      writer    63108
744      745   42      M      writer    55113
771      772   50      M      writer    27105
789      790   27      M  technician    80913
800      801   22      M      writer    92154
811      812   22      M  technician    76234
828      829   48      M      writer    80209
831      832   24      M  technician    77042
832      833   34      M      writer    90019
841      842   40      M      writer    93055
849      850   34      M  technician    78390
852      853   49      M      writer    40515
888      889   24      M  technician    78704
895      896   28      M      writer    91505

## Quants elements hi ha al filtre anterior?

In [12]:
# Opció utilitzant len()
#len(df[(df['gender'] == 'M') & (df['occupation'].isin(['technician', 'writer']))])
df[(df['gender'] == 'M') & (df['occupation'].isin(['technician', 'writer']))].shape[0]

52

## Agafa aleatòriament 10 files del DataFrame.

**Pista**: `sample()`

In [13]:
aleatori = df.sample(n=10)
print(aleatori)

     user_id  age gender     occupation zip_code
332      333   47      M          other    V0R2M
180      181   26      M      executive    21218
442      443   35      M       salesman    33308
397      398   40      M          other    60008
252      253   26      F      librarian    22903
783      784   47      M  administrator    91040
68        69   24      M       engineer    55337
870      871   31      M      executive    44648
701      702   37      M          other    89104
925      926   49      M  entertainment    01701

## Agafa aleatòriament 3 elements del DataFrame que treballen al codi postal `55337`.

In [14]:
ale_code_zip = df[df['zip_code'] == '55337'].sample(n=3, replace=True)
print(ale_code_zip)

     user_id  age gender     occupation zip_code
883      884   44      M       engineer    55337
68        69   24      M       engineer    55337
878      879   33      F  administrator    55337

## Ordena el conjunt de dades segons l'edat, de més gran a més jove.

In [15]:
age_ordenats = df.sort_values(by=['age'], ascending=False)
print(age_ordenats)

     user_id  age gender     occupation zip_code
480      481   73      M        retired    37771
859      860   70      F        retired    48322
802      803   70      M  administrator    78212
766      767   70      M       engineer    00000
558      559   69      M      executive    10022
..       ...  ...    ...            ...      ...
627      628   13      M           none    94306
673      674   13      F        student    55337
288      289   11      M           none    94619
470      471   10      M        student    77459
29        30    7      M        student    55436

[943 rows x 5 columns]

## Ordena el conjunt de dades per edat com abans, però assegura't que les persones amb la mateixa edat s'ordenen ascendentment per `user_id` (els `user_ids` més petits van abans).

In [16]:
age_ordenats_user_ids_1 = df.sort_values(by=['age', 'user_id'] , ascending = [False,True])
print(age_ordenats_user_ids_1)

     user_id  age gender     occupation zip_code
480      481   73      M        retired    37771
766      767   70      M       engineer    00000
802      803   70      M  administrator    78212
859      860   70      F        retired    48322
558      559   69      M      executive    10022
..       ...  ...    ...            ...      ...
673      674   13      F        student    55337
879      880   13      M        student    83702
288      289   11      M           none    94619
470      471   10      M        student    77459
29        30    7      M        student    55436

[943 rows x 5 columns]

## Elimina totes les files amb ocupació `other`.

## Elimina les columnes gender i user_id.

In [17]:

print(df.iloc[2:5, 0:2])

   user_id  age
2        3   23
3        4   24
4        5   33

## Canvia el nom de la columna `occupation` per `job`.

## Filtra les files que tenen una edat igual a un dels nombres següents: [19, 43, 26, 12]

**Pista**: `isin()`

## Crea una nova columna `age_range` que tingui 3 valors possibles:
- 0 si l'individu té menys de 25 anys.
- 1 si l'individu té entre 26 i 65 anys.
- 2 si l'individu té més de 65 anys.

In [5]:
import ipykernel
print("Kernel:", ipykernel.get_connection_file())

Kernel: c:\Users\fundacion\AppData\Roaming\jupyter\runtime\kernel-v3d5d54519af2fa4301eaa40f16f51943130f5bbb2.json